//@version=4
study(title="Envelope", shorttitle="Env", overlay=true, resolution="")

//Input values
len = input(65, title="Look Back", minval=1)
ref = input(26, title="EMA")
src = input(close, title="Source")

//percent = input(10.0)
//exponential = input(true)



//Main
basis = ema(src, ref)
width = basis - src



k = percent/100.0
upper = basis * (1 + k)
lower = basis * (1 - k)
plot(basis, "Basis", color=#FF6D00)
u = plot(upper, "Upper", color=#2962FF)
l = plot(lower, "Lower", color=#2962FF)
fill(u, l, color=color.rgb(33, 150, 243, 95), title="Background")